apiVersion: v1
kind: ReplicationController
metadata:
  name: my-app-rc
  labels:
    app: my-app
    type: frontend
spec:
  template:
    # Here goes a the pod definition
    metadata:
      name: my-app-pod
      labels:
        app: my-app
        type: frontend
    spec:
      containers: # List / Array
        - name: nginx-container
          image: nginx
  replicas: 3
